[package]
name = "konfig"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0.100", features = ["derive"] }
itoa = "1"
ryu = "1"
thiserror = "1"
pest_consume = "1.0"
pest = "2.1"

[dev-dependencies]
indoc = "2.0"
serde_yaml = "0.9"
ron = "0.8"
indexmap = { version = "1.9", features = [ "serde-1" ] }
