[package]
name = "konfig"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "^1.0.100", features = ["derive"] }
itoa = "^1.0.0"
ryu = "^1.0.0"
thiserror = "^1.0.0"

[dev-dependencies]
indoc = "2.0.1"
serde_yaml = "0.9.21"
indexmap = { version = "1.9.3", features = [ "serde-1" ] }
