name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Install cargo hack
        run: cargo install cargo-hack
      - name: Build test feature combinations
        run: RUSTFLAGS="-D warnings" cargo hack check --feature-powerset --no-dev-deps
      - name: Run tests
        run: RUSTFLAGS="-D warnings" cargo tarpaulin --out Xml
      - name: Upload to codecov
        run: bash <(curl -s https://codecov.io/bash)
